### ISSUE TITLE
Out of Memory exception for certain websites

### ISSUE THREAD

**Issue by meyntony** [Zeegaan/WebCrawlerFunc#1]
`{
    "OldUrl": "https://relyonnutec.com",
    "NewUrl": "https://relyonnutec.com",
    "Level": 0,
    "PercentageEquals": 0.95,
    "ContinueIfNoMatch": false,
    "DefaultRequestHeaders" : {}
}`

For the above payload we get an error:
`Executed 'Functions.WebCrawler' (Failed, Id=61ab6f0a-aa09-4c45-9cd0-2d268e39fdbd, Duration=4404ms)
 System.Private.CoreLib: Exception while executing function: Functions.WebCrawler. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Array dimensions exceeded supported range.)
  ---> System.OutOfMemoryException: Array dimensions exceeded supported range.
    at WebCrawler.PercentageCalculator.ComputeLevenshteinDistance(String source, String target) in C:\UmbracoRepos\WebCrawlerFunc\Webcrawlerproj\WebCrawler\PercentageCalculator.cs:line 42
    at WebCrawler.PercentageCalculator.CalculateSimilarity(String source, String target) in C:\UmbracoRepos\WebCrawlerFunc\Webcrawlerproj\WebCrawler\PercentageCalculator.cs:line 19
    at WebCrawler.ResponseComparer.CompareHtmlPercentage(String responseOne, String responseTwo) in C:\UmbracoRepos\WebCrawlerFunc\Webcrawlerproj\WebCrawler\ResponseComparer.cs:line 34
    at WebCrawler.WebCrawler.CompareResponse(Uri domainOld, Uri domainNew, Int32 currentLevel, Double percentageEquals, IDictionary`2 defaultRequestHeaders) in C:\UmbracoRepos\WebCrawlerFunc\Webcrawlerproj\WebCrawler\WebCrawler.cs:line 124
    at WebCrawler.WebCrawler.StartCrawlerAsync(Uri domainOld, Uri domainNew, IDictionary`2 defaultRequestHeaders, Int32 level, Double percentageEquals, Boolean continueIfNoMatch) in C:\UmbracoRepos\WebCrawlerFunc\Webcrawlerproj\WebCrawler\WebCrawler.cs:line 36
    at AzureWebCrawler.WebcrawlerFunc.Run(HttpRequestData req, FunctionContext executionContext) in C:\UmbracoRepos\WebCrawlerFunc\AzureWebCrawler\WebcrawlerFunc.cs:line 39
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
    at System.Threading.Tasks.Task`1.get_Result()
    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
 --- End of stack trace from previous location ---
    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
 --- End of stack trace from previous location ---
    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169
Stack:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
    at System.Threading.Tasks.Task`1.get_Result()
    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
 --- End of stack trace from previous location ---
    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
 --- End of stack trace from previous location ---
    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 169.`

**Comment by bergmania** [comment]
Maybe we should use https://www.nuget.org/packages/Fastenshtein/ 

```c#
int levenshteinDistance = Fastenshtein.Levenshtein.Distance("value1", "value2");
```

**Comment by Zeegaan** [comment]
Hello @meyntony and thank you for the issue :D 

As suggested I've now implemented the Fastenshtein package instead of my own percentage calculator.
I've tested this and it handles your request just fine now 👍
